name: Run Azure Login
on: 
  workflow_dispatch:
jobs: 

  az-login-test-non-oidc:
    runs-on: ubuntu-latest
    steps:
      - name: init install
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          which az
          az login --service-principal --tenant 21fadfa6-aa44-4433-ad30-81f4941512e4 --username 1c26eebb-2fd0-4981-995a-b3a5731cd448  --password  ${{ secrets.AZURE_PASS }}

      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_PASS }}
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          environment: "azurecloud"
      - name: test1
        run: |
           az account list 

