name: Hello World
on: push
jobs:
  approved:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - run: echo "This PR was approved"
  my_first_job:
    name: My first job
    runs-on: ubuntu-latest
    steps:
    - name: hello world action step
      id: hello
      uses: tanzhiliangit/hello-world-docker-action@v2
      with:
        who-to-greet: 'tzl'
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"
  my_second_job:
    name: My second job
    runs-on: macos-latest
    steps:
    - name: Run a multi-line script
      env:
        MY_VAR: Hello World!
        MY_NAME: P3TERX
      run: |
        echo $MY_VAR
        echo My name is $MY_NAME
        echo $GITHUB_REF
